### PR TITLE
add recommendation for visualize docker containers

### PR DESCRIPTION
**Pull request by daveyx**

### CODE REVIEW

**Comment by daveyx** [comment]
#60

**Comment by daveyx** [comment]
Hi @metas-ts 
i understand the concerns, i did not think about that and will follow your instructions

**Comment by daveyx** [comment]
Hi @metas-ts,
just finished the forum post (en only) and the reference of it in the doc in this PR

**Comment by metas-ts** [comment]
great, thx a lot!

**Pull request merged**
