### PR TITLE
Revert "[fix link] menu.md"

### PR DESCRIPTION
**Pull request by metasnw**
Reverts metasfresh/metasfresh-documentation#133

### CODE REVIEW

**Comment by metasnw** [comment]
@MZorzy had to revert your change as the link wasnt working. you need to specify links to ".md" files without ".md" extension to make them work.

**Comment by MZorzy** [comment]
?
from https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_webui_collection/EN/InitialSetupWizard.md if click on blu 'menu' i'm redirect to 404 page.
with .md open correct page.

crome on samsung tab s2

**Comment by MZorzy** [comment]
like https://github.com/blog/1395-relative-links-in-markup-files
without .md i'm redirected to 404 page on crome on samsung tab s2.
same on pc+firefox 55.0.3

**Comment by metasnw** [comment]
@MZorzy please use the documentation using the rendered output: 
http://docs.metasfresh.org/webui_collection/EN/InitialSetupWizard.html

**Comment by MZorzy** [comment]
ooops sorry.
look/work ok on "doc" site

**Pull request merged**
