### PR TITLE
Described enhanced pricing in EN+DE

### PR DESCRIPTION
**Pull request by metas-Kay**
- reorganized and resequenced pricing section
- improved docs on autom.vol. discount
- synced and corrected documentation

(this is about and subsequent to issue #299 )

### CODE REVIEW

**Review by metas-dh — COMMENTED** [review]
in "Improved docs on autom.vol. discount in EN+DE"
+title: How do I link a discount scheme to a buiness partner?
=> spelling mistake

**Review by metas-dh — COMMENTED** [review]
in "Described Enhanced Pricing in EN+DE":
regarding "Pricing conditions in metasfresh": "The business partner *must be* linked to the exact same price list that includes the products. 
=> that's not entirely correct: You can leave the pricelist field empty in the vendor or customer tab, bpartner window, you then have to manually select the pricelist in purchase or sales order, before you can add products to the orderlines.

**Comment by metas-Kay** [comment]
Hi @metas-dh!
Thank you for your review.
I corrected the spelling mistakes (buiness > business, and scheme > schema) in the first commit, and adjusted the pricing conditions docs according to your comment in the second one. (see descriptions)

Please review and merge these PRs, provided no further amendments are needed.

Would you please also check this issue I created in https://github.com/metasfresh/metasfresh/issues/4226?
I believe it is a bug. If you deem it helpful and important, would you please assign it to the experts and label it? I do not yet have permission to do so myself. Thank you in advance!

**Review by metas-dh — APPROVED** [review]
Thx for the update.

**Pull request merged**
